### PR TITLE
DO NOT USE THIS

### PR DESCRIPTION
**Pull request by deads2k**
@ironcladlou This demonstrates where the correct codec is. DO NOT MERGE THIS INTO YOUR BRANCH.

@smarterclayton Any strong objection to exposing `Codec()` from `resource.RESTClient`?  This change would require it.  The knowledge is needed for proper encoding.

### CODE REVIEW

**Comment by deads2k** [comment]
produces
```
[deads@deads-dev-01 origin]$ make build && oc create -f examples/hello-openshift/hello-pod.json --loglevel=8
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries
hack/build-go.sh took 22 seconds
I1009 14:31:17.194099    6246 decoder.go:141] decoding stream as JSON
I1009 14:31:17.196734    6246 debugging.go:98] GET https://localhost:8443/api
I1009 14:31:17.196755    6246 debugging.go:105] Request Headers:
I1009 14:31:17.196764    6246 debugging.go:108]     User-Agent: oc/v1.1.0 (linux/amd64) kubernetes/86b4e77
I1009 14:31:17.196773    6246 debugging.go:108]     Authorization: Bearer 8NueGFcC2_etolZb87qwgFcejTOyFjPjGMP9sa9FjNk
I1009 14:31:17.213178    6246 debugging.go:123] Response Status: 200 OK in 16 milliseconds
I1009 14:31:17.213204    6246 debugging.go:126] Response Headers:
I1009 14:31:17.213214    6246 debugging.go:129]     Date: Fri, 09 Oct 2015 18:31:17 GMT
I1009 14:31:17.213222    6246 debugging.go:129]     Content-Length: 32
I1009 14:31:17.213231    6246 debugging.go:129]     Cache-Control: no-store
I1009 14:31:17.213239    6246 debugging.go:129]     Content-Type: application/json
I1009 14:31:17.213268    6246 request.go:788] Response Body: {
  "versions": [
    "v1"
  ]
}
W1009 14:31:17.213465    6246 helper.go:231] Server does not support API version 'v1beta3'. Falling back to 'v1'.
#### helper.RESTClient codec version: v1 &{0xc2080f0e10 v1}
I1009 14:31:17.215008    6246 request.go:490] Request Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"hello-openshift","namespace":"foo","creationTimestamp":null,"labels":{"name":"hello-openshift"}},"spec":{"volumes":[{"name":"tmp","emptyDir":{}}],"containers":[{"name":"hello-openshift","image":"openshift/hello-openshift","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"tmp","mountPath":"/tmp"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{},"privileged":false}}],"restartPolicy":"Always","dnsPolicy":"ClusterFirst"},"status":{}}
I1009 14:31:17.215046    6246 debugging.go:98] POST https://localhost:8443/api/v1/namespaces/foo/pods
I1009 14:31:17.215060    6246 debugging.go:105] Request Headers:
I1009 14:31:17.215069    6246 debugging.go:108]     User-Agent: oc/v1.1.0 (linux/amd64) kubernetes/86b4e77
I1009 14:31:17.215080    6246 debugging.go:108]     Authorization: Bearer 8NueGFcC2_etolZb87qwgFcejTOyFjPjGMP9sa9FjNk
I1009 14:31:17.219948    6246 debugging.go:123] Response Status: 201 Created in 4 milliseconds
I1009 14:31:17.219990    6246 debugging.go:126] Response Headers:
I1009 14:31:17.220005    6246 debugging.go:129]     Cache-Control: no-store
I1009 14:31:17.220017    6246 debugging.go:129]     Content-Type: application/json
I1009 14:31:17.220028    6246 debugging.go:129]     Date: Fri, 09 Oct 2015 18:31:17 GMT
I1009 14:31:17.220039    6246 debugging.go:129]     Content-Length: 1198
I1009 14:31:17.220084    6246 request.go:788] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"hello-openshift","namespace":"foo","selfLink":"/api/v1/namespaces/foo/pods/hello-openshift","uid":"edc7fd0d-6eb3-11e5-8557-28d2447dc82b","resourceVersion":"388","creationTimestamp":"2015-10-09T18:31:17Z","labels":{"name":"hello-openshift"},"annotations":{"openshift.io/scc":"restricted"}},"spec":{"volumes":[{"name":"tmp","emptyDir":{}},{"name":"default-token-4r0fu","secret":{"secretName":"default-token-4r0fu"}}],"containers":[{"name":"hello-openshift","image":"openshift/hello-openshift","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"tmp","mountPath":"/tmp"},{"name":"default-token-4r0fu","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{},"privileged":false,"seLinuxOptions":{"level":"s0:c6,c0"},"runAsUser":1000030000}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","imagePullSecrets":[{"name":"default-dockercfg-z5k76"}]},"status":{"phase":"Pending"}}
```

**Comment by smarterclayton** [comment]
We had tried to avoid adding things to the RESTClient public interface
(just to keep it small).  Resource Helper already has codec as a member.

**Comment by smarterclayton** [comment]
Is the ResourceHelper Codec != the rest client codec for some reason?

**Comment by ironcladlou** [comment]
Turns out the client isn't negotiating with the server when doing `create -f ...`, which is the root of the problems.

**Pull request closed without merging**
